### ISSUE TITLE
Composer: Could not scan for classes inside "newsletter//tests/behat/"

### ISSUE THREAD

**Issue by dallumnz** [silverstripe-labs/silverstripe-newsletter#108]
Ignoring the [tests folder](https://github.com/silverstripe-labs/silverstripe-newsletter/blob/master/.gitattributes#L1) for export creates an issue with composer when using  --prefer-dist 

Composer downloads the zip package without the /tests folder, however in [composer.json](https://github.com/silverstripe-labs/silverstripe-newsletter/blob/master/composer.json#L24) you have "classmap": ["tests/behat/"]

resulting in
```
[RuntimeException]
Could not scan for classes inside "newsletter//tests/behat/" which does not appear to be a file nor a folder
```

**Comment by tractorcow** [comment]
The fix for this is to change .gitattributes to not ignore the entire tests folder, but only the non-behat folders within this.

**Comment by dhensby** [comment]
I think a better solution is to use https://getcomposer.org/doc/04-schema.md#autoload-dev

**Comment by dhensby** [comment]
Is the classmap *required* for the tests to run or just an efficiency issue?

**Comment by tractorcow** [comment]
It's required to load some classes for behat, it seems.

**Comment by tractorcow** [comment]
autoload-dev is root only =(

**Comment by dhensby** [comment]
blergh

**Comment by tractorcow** [comment]
Remove `/tests` from .gitattributes and replace with
```
/tests/phpcs export-ignore
/tests/travis export-ignore
/tests/unit export-ignore
```

**Comment by dhensby** [comment]
Fixed
