### ISSUE TITLE
Messages stay queued

### ISSUE THREAD

**Issue by luukgruijs** [silverstripe-labs/silverstripe-newsletter#85]
Hi,

i installed the newsletter module with the messagequeue module but when i send a message to my subscribers it stays queued forever. 

There are more people with this problem: http://www.silverstripe.org/community/forums/all-other-modules/show/23056

Any idea on how to solve this?

Thanks in advance

**Comment by jedateach** [comment]
sygmoral's solution appeared to work for me:

In mysite/_config.php, add:
```php
MessageQueue::set_onshutdown_option('phppath', PHP_BINDIR . '/php');
```

**Comment by jedateach** [comment]
I also wonder if newsletter module should be modified to suggest the message queue module in composer, rather than require.

**Comment by bbstuntman** [comment]
@jedateach Your solution apparently seems to work on localhost env. Won't work on SS 3.2, but with the 3.1.5 it's ok by now.. i will give it a check on server evn
