### ISSUE TITLE
Image URL's not working correctly

### ISSUE THREAD

**Issue by dleinbach** [silverstripe-labs/silverstripe-newsletter#87]
When I add a images to my newsletter the img path seems to be broken.  I have used the the following code in my config file but once thats in, i get locked out of the admin section of silverstripe. 

Config::inst()->update( 'Director', 'alternate_base_url', 'http://www.mysite.com/' );

Any help would be greatly appreciated.

**Comment by jedateach** [comment]
@dleinbach might need to check your $_FILE_TO_URL_MAPPING is set up correctly. This is because the message queue module performs operations from the command line.
see http://doc.silverstripe.org/en/developer_guides/cli

**Comment by dleinbach** [comment]
@jedateach You are the man!  that worked great!
